### ISSUE TITLE
Don't delete entire directories

### ISSUE THREAD

**Issue by belaban** [belaban/jgroups-raft#150]
Some implementations of `Log.delete()` call `FileUtils.deleteDirectory()`. This is dangerous if someone inadvertently sets `RAFT.log_dir` to some directory whose contents should not be removed. Usually not an issue because (e.g. LevelDBLog) creates its own directory, but better safe than sorry!
Solution: a log impl should only remove the files it creates. Example: LevelDBLog should not call `FileUtils.removeDirectory()`, but `DBFactory.destroy()` instead: this way, LevelDB takes care of removing the files it created.

**Comment by franz1981** [comment]
Another point related correctness: few raft impl are handling delete/move/rename of log files correctly AFAIK
In theory  they should (and we, as well) call `FileChannel::force(true)` on the owning directory/parent folder in order to save metadata on filesystem and while restarted (or on a machine crash) file system metadata are able to find/not find whatever changes has been persisted.

**Comment by belaban** [comment]
Fixed by #149 
@franz1981 Can you create a separate issue re your comment?
