### ISSUE TITLE
Understanding failure cases in this code

### ISSUE THREAD

**Issue by osheroff** [belaban/jgroups-raft#79]
Hi @belaban, 

I'm Osheroff, I write Maxwell (https://github.com/zendesk/maxwell).  I'm looking around at JVM solutions that can do HA without the need for external dependencies.  jgroups-raft and atomix seem to be the only games in town (unless you know of others?), and while both projects appear... slumbering, your code actually seems to work properly and atomix's doesn't.  

So I'm considering pulling in jgroups-raft.  My only use case is for leader election, aka implement a singleton service.  

Running the code locally, there's one seemingly ugly failure case:

- start nodes A, B, C
- A becomes leader
- Simulate a network partition of {A}, and {B, C} by killing {B, C}
- A happily continues to lead

if my understanding is correct, shouldn't A automatically have to step down in this case, because {B, C} could elect a leader on the other side of the partition?  Is there a work-around?  Should each node need to perform a write operation to the raft cluster periodically?

More broadly (and without judgement), am I crazy for wanting to put this into heavy-duty production code?

thanks for your time,
osheroff

**Comment by belaban** [comment]
Hi @osheroff 
if A ends up in a single partition, it will continue to be leader, but it will not be able to *commit* any changes.

Meanwhile, B becomes leader in `{A,B}` and does *commit* changes. When A and `{B,C}` merge, the (uncomitted) modifications by A will be dropped.

A does not step down as a leader because there will be another election anyway when the partition heals, so this is just an optimization. Note that there an issue for this already: https://github.com/belaban/jgroups-raft/issues/17.

With respect to maturity: jgroups-raft stands on the shoulders of JGroups, so there's already a lot of maturity (JGroups has been in prod for 2 decades). The code is relatively small, and it adheres more or less strictly to the Raft spec, so there shouldn't be a lot of bugs you'll run into.

I know that some people have acked that their code using jgroups-raft is running in production.
May be worth asking on the ML...
Cheers

**Comment by osheroff** [comment]
thanks for the reply!

> A does not step down as a leader because there will be another election anyway when the partition heals, so this is just an optimization.

I see, yeah.  For the data inside the raft cluster, that's true.  But my goal here is to use the results of the election as a distributed lock for an external service (in this case, a singleton instance of a daemon).  In a split brain scenario I could end up with data duplication.  

I'll play around with requiring a commit to succeed periodically. 

Any pointers if I decided to poke around at an implementation of #17?

**Comment by belaban** [comment]
The leader stepping down won't fix this 100%, because views `{A}` (installed in A) and `{BC}` (installed in B and C) may not be installed at the same time; if the `{B,C}` view is installed first, there's a small window during which we'll have 2 leaders and therefore the possibilty of both holding the same lock (or both being singletons).
I'm writing a blog post on this on http://belaban.blogspot.com/, stay tuned...

**Comment by osheroff** [comment]
Looking forward to your post.

Sounds like it would be an imperfect lock, which is... mostly fine for my use case.  A small overlap would result in a small amount of duplicated data written to a Kafka stream, which is more or less within my specs.  But having the situation continue Uncorrected would be unfortunate.

I can sort of work around the leader not stepping down by checking for timeouts while writing to the raft cluster, but it seems an imperfect solution at best; getting the leader to step down by itself would be much preferred.

**Comment by belaban** [comment]
Hi Ben @osheroff 
I think if you register a RAFT.RoleChange listener, you should get notified when a Leader steps down and becomes a Candidate (or Follower) again. I think I'll fix #17 relatively soonish.
Cheers,

**Comment by belaban** [comment]
I think I'll implement a lock service in jgroups-raft, early next week, plus fix #17. This way, we'd ensure that there's only 1 lock holder at any given time.

**Comment by belaban** [comment]
Here's a preview; feedback welcome. Not yet polished, will publish it next week
[1] https://www.blogger.com/blog/post/edit/preview/19835054/1923748738341142742

**Comment by osheroff** [comment]
@belaban the blogger link is 404ing.  but very much looking forward to your changes!

**Comment by belaban** [comment]
Oops, sorry, perhaps preview-links don't work, but the post will be available Monday. Cheers

**Comment by belaban** [comment]
http://belaban.blogspot.com/2020/11/i-hate-distributed-locks.html

**Comment by belaban** [comment]
OK, so I implemented #17 [1] and will rebase/merge shortly. I'll also upgrade to JGroups 5.1.

[1] https://github.com/belaban/jgroups-raft/issues/17

**Comment by belaban** [comment]
Hi @osheroff done!
While at it, I fixed quick fluctuations between Candidates and Followers (https://github.com/belaban/jgroups-raft/issues/81) and changed names to be more legible (https://github.com/belaban/jgroups-raft/issues/82). I subsequently released a 0.5.3.Final (branch: 0.5).
I then upgraded to JGroups 5.1.2.Final and released 1.0.0.Final (branch: master). Fixing #17 should get you going.
Cheers,

**Comment by osheroff** [comment]
thanks a lot @belaban!  https://github.com/zendesk/maxwell/pull/1609  opened, things seem good locally wrt to stepping down.  I'll be interested to see how this code works out in the wild; I presume that the failure scenarios out there are gnarlier and more varied than I can imagine.

**Comment by belaban** [comment]
Sounds good! Let me know how this goes...
