### ISSUE TITLE
[QUESTION] Asynchronous commit phase

### ISSUE THREAD

**Issue by hypnoce** [belaban/jgroups-raft#85]
In the current implementation, once the leader has received the majority of AppenEntriesResponse, it commits its log.

https://github.com/belaban/jgroups-raft/blob/7bd4a5596b1495d224930d015c51833c7931e3f1/src/org/jgroups/protocols/raft/Leader.java#L45

Nevertheless, it does not send a commit message to the followers just after committing itself. It does so in the resend thread every `resend_interval`.
https://github.com/belaban/jgroups-raft/blob/7bd4a5596b1495d224930d015c51833c7931e3f1/src/org/jgroups/protocols/raft/RAFT.java#L641

As seen in your design documents
https://github.com/belaban/jgroups-raft/blob/7bd4a5596b1495d224930d015c51833c7931e3f1/doc/design/AppendEntries.txt#L60
it would be valid (and more optimal ?) to actually send commit messages just after the leader commit.

Waiting `resend_interval` can create unnecessary latency for state machine update on the followers.

@belaban What is your opinion on that ? Do you think adding an option to send append entries with the leader commit can be useful ?

**Comment by belaban** [comment]
Hi @hypnoce 
the problem is that this may possibly generate a lot of traffic (as mentioned in the design document). Worst case is that a MessageBatch is received: for each message, we call Leader.handleAppendEntriesResponse(), which would then send N messages to all participants.
Also, we'd have to check for deadlocks, as the receiving code handles the commit in a synchronized statement.

Can you instead reduce `resend_interval`? This would ensure a more timely reception of commits by the participants.

If this doesn't work for you, we _can_ introduce this change, but it should be controlled by an attribute in `RAFT` (`send_commits_immediately`?) which should by default by off.

**Comment by hypnoce** [comment]
I tried something on a branch locally : https://github.com/hypnoce/jgroups-raft/commit/93a9160560d503aa5c324c45f7e1a2925b996f27.
It does send to all followers only when majority is obtained. Not when receiving further responses from late followers.
Let me know what you think about this solution.

**Comment by belaban** [comment]
Morning @hypnoce 
the problem is that the upcall `handleAppendEntriesResponse()` is called in  synchronized block. It then sends the commit message within that synchronized block, which (IMO) is a smell... Can this be delayed until after the synchronized block?
OTOH, this is all goverened by the 'send_commits_immediately` attribute, so it can be disabled (default)...
I'll apply your PR, but please do investigate the moving of the send out of the synchronized block and - if feasible - submit another PR.

**Comment by hypnoce** [comment]
Hey @belaban ,

after inspection, I do not see where we reach a synchronised block in the `handleAppendEntriesResponse()`. We have a synchronised in the `handleCommit` and `commitLogTo`. Did I miss something ?

Thanks

**Comment by belaban** [comment]
Sorry, it's in `handleAppendEnriesResponse()`, which calls synchronized `handleCommit()`. But, IIRC, you wanted to send the message _after_ `handleCommit()`, not within it? That should be fine.
As I said, take a look and if you feel confident, send me a PR. This is not a critical change anyway, as the send is conditioned upon `send_commits_immediately` anyway...

**Comment by hypnoce** [comment]
Indeed, the send is done outside of the `handlecommit` scope. PR done.
